jwt:
    secret: '[a-z-A0-9]-<secret'

server:
    port: 8081

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/DB_SECURITY_ROLES
        username: root
        password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update #create update
        generate-ddl: false
    version: 0.0.3
#    Evitar que espring maneje esta configuracion cuando no encuentra un recurso
#    mvc:
#     throw-exception-if-no-handler-found: true
#    web:
#      resources:
#        add-mappings: false
     


# #Data source 
# #Indica el driver/lib para conectar java a mysql
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# #Url donde esta el servicio de tu mysql y el nombre de la base de datos
# spring.datasource.url=jdbc:mysql://localhost:3306/DB_SECURITY_ROLES

# #Usuario y contrasena para tu base de datos descrita en la linea anterior
# spring.datasource.username=root
# spring.datasource.password=admin

# #[opcional]Imprime en tu consola las instrucciones hechas en tu base de datos.
# spring.jpa.show-sql = true

# #spring.jpa.hibernate.ddl-auto = create-drop
# spring.jpa.generate-ddl = false

# #ruta personalizada swagger
# springdoc.api-docs.path=/api-docs